add fix flag to lint-go

diff --git a/run/lint-go/command b/run/lint-go/command
--- a/run/lint-go/command
+++ b/run/lint-go/command
@@ -1,13 +1,50 @@
 #!/usr/bin/env bash
 set -e
 
+function display_help() {
+	cat <<EOF
+Usage: mrt run $(basename "$(dirname "$0")") [OPTIONS]
+
+Lint Go files with various options.
+
+Options:
+  --fix      Automatically fix formatting issues.
+  -h|--help  Display this help message and exit.
+EOF
+}
+
 rootDir="$1"
 shift
+fix=false
+
+while [[ $# -gt 0 ]]; do
+	case "$1" in
+	"--fix")
+		fix=true
+		shift
+		;;
+	"-h" | "--help")
+		display_help
+		exit 0
+		;;
+	--*)
+		echo "Error: Unknown option '$1'."
+		echo
+		display_help
+		exit 1
+		;;
+	esac
+done
+
+fix_flag=""
+if [[ "$fix" == true ]]; then
+	fix_flag="--fix"
+fi
 
 cd "$rootDir/app"
-golangci-lint run --config "$rootDir"/.golangci.yml --timeout 10m
+golangci-lint run $fix_flag --config "$rootDir"/.golangci.yml --timeout 10m
 go vet ./...
 
-cd "$rootDir/e2e-tests"
-golangci-lint run --config "$rootDir"/.golangci.yml --timeout 10m
+cd "$rootDir/go-e2e"
+golangci-lint run $fix_flag --config "$rootDir"/.golangci.yml --timeout 10m
 go vet ./...
