Add manual/ci run mode for e2e tests run command
When switching between localhost and github.com for testing I sometimes get issues with the known_hosts file. Thus I make it more visible. If you pass the --manual flag (this flag is default) it tests the ssh connection. This will show if there are any errors. On the CI we don't want that, that is why we skip it on the runner.

diff --git a/run/e2e-tests/command b/run/e2e-tests/command
--- a/run/e2e-tests/command
+++ b/run/e2e-tests/command
@@ -4,6 +4,8 @@ set -e
 FLAG_LOCAL="--local"
 FLAG_REMOTE="--remote"
 FLAG_CLEAN="--clean"
+FLAG_MANUAL="--manual"
+FLAG_CI="--ci"
 FLAG_HELP="-h|--help"
 
 declare -A HOSTNAME_MAP=(
@@ -20,6 +22,7 @@ Run end-to-end tests with various options.
 Options:
   $FLAG_LOCAL|$FLAG_REMOTE   Use the local gitlab or github.com to run e2e-tests (default: remote).
   $FLAG_CLEAN            Perform a clean build before running the tests.
+  $FLAG_MANUAL|FLAG_CI   Determines whether tests are run manually or on from CI.
   $FLAG_HELP          Display this help message and exit.
 
 FILES:
@@ -31,6 +34,7 @@ EOF
 rootDir="$1"
 shift
 clean_build=false
+run_mode="$FLAG_MANUAL"
 hostname="${HOSTNAME_MAP[$FLAG_REMOTE]}"
 declare -a files
 
@@ -42,6 +46,10 @@ while [[ $# -gt 0 ]]; do
 		;;
 	"$FLAG_CLEAN")
 		clean_build=true
+		shift
+		;;
+	"$FLAG_MANUAL" | "$FLAG_CI")
+		run_mode="$1"
 		shift
 		;;
 	"$FLAG_HELP")
@@ -61,6 +69,35 @@ while [[ $# -gt 0 ]]; do
 	esac
 done
 
+SSH_CONFIG_FILE="$rootDir/.ssh/config"
+PRIVATE_KEY_FILE="$rootDir/.ssh/private-key"
+HOST_ALIAS="github-testing"
+
+if [[ ! -f "$PRIVATE_KEY_FILE" ]]; then
+	echo "Error: Private key file not found at $PRIVATE_KEY_FILE"
+	exit 1
+fi
+
+mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
+# Normally you would add "User git" to the config. But somehow this does not work on the ci. There I have to remove
+# the user from the config.
+cat <<EOF >"$SSH_CONFIG_FILE"
+Host $HOST_ALIAS
+   HostName $hostname
+EOF
+
+if [[ "$run_mode" == "$FLAG_MANUAL" ]]; then
+	GITHUB_RESPONSE_MATCH="successfully authenticated"
+	GITLAB_RESPONSE_MATCH="Welcome to GitLab"
+
+	# Since "User git" is not in the config. (see above) I have to explicitly use it in the ssh access check below.
+	if ! ssh -F "$SSH_CONFIG_FILE" -T "git@$HOST_ALIAS" 2>&1 | grep -qE "$GITHUB_RESPONSE_MATCH|$GITLAB_RESPONSE_MATCH"; then
+		echo "Error: Could not establish SSH connection to $HOST_ALIAS."
+		echo "Error: Please verify if the private key is correct."
+		exit 1
+	fi
+fi
+
 e2eTestDir="$rootDir/e2e-tests"
 
 if [[ "$clean_build" == true ]]; then
@@ -75,14 +112,6 @@ fi
 
 echo "Test files to be executed:"
 printf "\t%s\n" "${files[@]}"
-
-SSH_CONFIG_FILE="$rootDir/.ssh/config"
-
-mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
-cat <<EOF >"$SSH_CONFIG_FILE"
-Host github-testing
-   HostName $hostname
-EOF
 
 echo "Running tests with BATS..."
 
