Add proper argument parsing and help function to e2e-tests run script

diff --git a/run/e2e-tests/command b/run/e2e-tests/command
--- a/run/e2e-tests/command
+++ b/run/e2e-tests/command
@@ -1,37 +1,87 @@
 #!/usr/bin/env bash
-
 set -e
 
-rootDir=$1
-shift
+FLAG_LOCAL="--local"
+FLAG_REMOTE="--remote"
+FLAG_CLEAN="--clean"
+FLAG_HELP="-h|--help"
 
-if [[ "$1" == "--clean" ]]; then
-	echo "Clean build for e2e-tests."
-	mrt --team-dir "$rootDir" run build
-	shift
+function display_help() {
+  cat <<EOF
+Usage: mrt run $(basename "$(dirname "$0")") [OPTIONS] [FILES...]
+
+Run end-to-end tests with various options.
+
+Options:
+  $FLAG_LOCAL|$FLAG_REMOTE   Use the local gitlab or github.com to run e2e-tests (default: remote).
+  $FLAG_CLEAN            Perform a clean build before running the tests.
+  $FLAG_HELP          Display this help message and exit.
+
+FILES:
+  List of specific .bats test files to be executed. If not provided,
+  the script will find all .bats files in the e2e-tests directory.
+EOF
+}
+
+rootDir="$1"; shift
+run_mode="$FLAG_REMOTE"
+clean_build=false
+declare -a files
+
+while [[ $# -gt 0 ]]; do
+  case "$1" in
+    $FLAG_LOCAL|$FLAG_REMOTE)
+      run_mode="$1"
+      shift
+      ;;
+    $FLAG_CLEAN)
+      clean_build=true
+      shift
+      ;;
+    $FLAG_HELP)
+      display_help
+      exit 0
+      ;;
+    --*)
+      echo "Error: Unknown option '$1'."
+      echo
+      display_help
+      exit 1
+      ;;
+    *)
+      files+=("$1")
+      ;;
+  esac
+  shift
+done
+
+echo "Run mode: $run_mode"
+
+if [[ "$clean_build" == true ]]; then
+  echo "Performing a clean build for e2e-tests..."
+  mrt --team-dir "$rootDir" run build
 else
-	echo "Using built binary to execute e2e-tests."
+  echo "Using built binary to execute e2e-tests."
 fi
 
-if [[ $# -eq 0 ]]; then
-	mapfile -t files < <(find "$rootDir/e2e-test" -type f -name "*.bats" ! -ipath "*/3rdParty/*")
-else
-	files=("$@")
+if [[ "${#files[@]}" -eq 0 ]]; then
+  echo "No specific test files provided. Auto-detecting *.bats files..."
+  mapfile -t files < <(find "$rootDir/e2e-test" -type f -name "*.bats" ! -ipath "*/3rdParty/*")
 fi
 
 echo "Test files to be executed:"
 printf "\t%s\n" "${files[@]}"
 
 export BATS_LIB_PATH="$rootDir/e2e-test/3rdParty/test_helper":"$rootDir/e2e-test/helpers"
-
 SSH_CONFIG_FILE="$rootDir/.ssh/config"
 PRIVATE_KEY_FILE="$rootDir/.ssh/private-key"
 
-cat <<EOF > $SSH_CONFIG_FILE
+mkdir -p "$(dirname "$SSH_CONFIG_FILE")"
+cat <<EOF > "$SSH_CONFIG_FILE"
 Host github-testing
    HostName github.com
 EOF
-
 export GIT_SSH_COMMAND="ssh -F $SSH_CONFIG_FILE"
 
+echo "Running tests with BATS..."
 "$rootDir"/e2e-test/3rdParty/bats/bin/bats "${files[@]}" --jobs 10
