Build back to not use tar packaging

diff --git a/run/build/command b/run/build/command
--- a/run/build/command
+++ b/run/build/command
@@ -18,19 +18,24 @@ help(){
 
 build_binary() {
   platform=$1
-  binaryLocation=$2
-
+  
+  binaryLocation="$("$rootDir/mrt" run binary-location "$platform")"
   GOOS="${platform%/*}"
   GOARCH="${platform#*/}"
 
   echo "Building for $platform..."
-    if ! env GOOS="$GOOS" GOARCH="$GOARCH" go build -o "$binaryLocation" .
-    then
-      echo "Error occurred while building for ${platform}"
-      exit 1
-    else
-      echo "Successfully build for ${platform}"
-    fi
+  if ! env GOOS="$GOOS" GOARCH="$GOARCH" go build -o "$binaryLocation" .
+  then
+    echo "Error occurred while building for ${platform}"
+    exit 1
+  else
+    echo "Successfully build for ${platform}"
+  fi
+}
+
+installToBuildFolder() {
+  binaryLocation=$("$rootDir"/mrt run binary-location "$("$rootDir/mrt" run detect-platform)")
+  cp "$binaryLocation" "$("$rootDir/mrt" run build-location)/mrt"
 }
 
 case $1 in
@@ -50,5 +55,10 @@ fi
 cd "$rootDir"/app
 for platform in "${platforms[@]}"
 do
-    build_binary "$platform" "$("$rootDir/mrt" run binary-location "$platform")"
+  build_binary "$platform"
 done
+
+if [[ "${platforms[*]}" =~ $("$rootDir/mrt" run detect-platform) ]]; then
+    installToBuildFolder
+fi
+
